"""
Filename: core/bid.py

Author: Santosh Purja Pun (punsantosh1991@outlook.com)

Description: This is the bid class. This class defines the structure of each bids generated by the traders.
"""

from options import opts

class Bid:
    def __init__(self, bidID, traderId, type, quantity, price, reservedPrice):
        self.bidID = bidID
        self.traderID = traderId
        self.type=type
        self.quantity = quantity
        self.price = price
        self.reservePrice = reservedPrice

    def getBidInfo(self, hideReservePrice = False):
        """
        Bid structure (bidID, traderID, traderType, Quantity, Price, ReservePrice)
        """
        if hideReservePrice == True:
            return '(' + str(self.bidID) + ', ' + str(self.traderID) + ', ' + self.type + ',' + str(self.quantity) + \
                   ', ' + opts['CURRENCY'] + str(self.price) + ')'

        return '(' + str(self.bidID) + ', ' + str(self.traderID) + ', ' + self.type + ',' + str(self.quantity) + \
               ', ' + opts['CURRENCY'] + str(self.price) + ', ' + opts['CURRENCY'] + str(self.reservePrice) +')'

    def updateQuantity(self, qty):
        self.quantity = qty

    def getBidAmount(self):
        return self.price

    def getQuantity(self):
        return self.quantity

    def getBidType(self):
        return self.type

    def getTraderID(self):
        return self.traderID

    def getReservedPrice(self):
        return self.reservePrice


